### ISSUE TITLE
Typo in polymer command in the read me

### ISSUE THREAD

**Issue by 0xvanbeethoven** [robertmartin8/MolecularNotes#1]
Hi Robert, loving my time with Molecular Notes so far. Just wanted to lyk there is a typo in the polymer command. 
It's: cd ObsidianVault && streamit run _scripts/polymer.py
when it should be: cd ObsidianVault && streamlit run _scripts/polymer.py

**Comment by robertmartin8** [comment]
Fixed, thank you!
